-- 特需儿童教育绘本/图卡生成系统 —— 建表脚本
-- 可重复执行（IF NOT EXISTS）

create table if not exists users (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  username    varchar unique not null,   -- 登录账号
  password    varchar not null,          -- bcrypt 哈希
  nickname    varchar,                   -- 显示昵称
  avatar      varchar                    -- 头像 URL（可空）
);

comment on table users is '用户表（账号密码登录）';

create table if not exists works (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now() not null,
  updated_at   timestamptz default now() not null,
  user_id      bigint references users(id),
  template_id  varchar,                  -- 对应 data/templates.ts 的模板 key
  title        varchar,                  -- 作品标题（模板名+主体）
  input_text   varchar,                  -- 用户填写内容（JSON 字符串）
  prompt       varchar,                  -- 拼接后的最终正向提示词
  status       varchar,                  -- PENDING / RUNNING / SUCCEEDED / FAILED
  task_id      varchar,                  -- DashScope 异步任务 id
  output_url   varchar                   -- 生成图 URL（DashScope 临时地址，24h 有效）
);

comment on table works is '生成作品表';

create index if not exists idx_works_user_created
  on works (user_id, created_at desc);

create index if not exists idx_works_task
  on works (task_id);

-- ============ 多页绘本 ============

create table if not exists books (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  title       varchar,
  brief       varchar,          -- 用户输入的故事描述
  options     jsonb,            -- 生成参数（年龄/类型/主题/角色/视角/页数/比例）
  status      varchar,          -- DRAFTING / ILLUSTRATING / DONE / FAILED
  page_count  integer
);

comment on table books is '多页绘本';

create table if not exists book_pages (
  id          bigint generated by default as identity primary key,
  book_id     bigint references books(id) on delete cascade,
  page_index  integer,          -- 0 起
  text        varchar,          -- 该页故事正文
  scene       varchar,          -- 该页画面描述（喂给生图）
  task_id     varchar,          -- 该页 DashScope 生图任务 id
  status      varchar,          -- PENDING/RUNNING/SUCCEEDED/FAILED
  image_url   varchar
);

comment on table book_pages is '绘本分页';

create index if not exists idx_books_user_created
  on books (user_id, created_at desc);

create index if not exists idx_pages_book
  on book_pages (book_id, page_index);

-- ============ 预设模板库 ============

create table if not exists templates (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now() not null,
  kind          varchar,        -- 'image' | 'book'
  topic         varchar,        -- 康复课题：language/social/selfcare/cognition
  style_key     varchar,        -- 风格 key
  title         varchar,
  subtitle      varchar,
  brief         varchar,        -- 预设生成描述（点模板后填入输入框）
  options       jsonb,          -- 预设参数
  prompt        varchar,        -- 生成缩略图用的最终提示词
  system_prompt text,           -- 「做同款」时追加的专家 prompt（构图/画风/避免事项等）
  cover_url     varchar,        -- 预生成的缩略图 URL
  sort          integer default 0
);
-- 已存在库补列（安全幂等）
alter table templates add column if not exists system_prompt text;

comment on table templates is '预设模板库';

create index if not exists idx_templates_kind_topic
  on templates (kind, topic);

-- 模板多页内容（绘本模板的逐页图文；图片模板可不建页）
create table if not exists template_pages (
  id           bigint generated by default as identity primary key,
  template_id  bigint references templates(id) on delete cascade,
  page_index   integer,       -- 0 起
  text         varchar,       -- 该页故事正文
  image_url    varchar        -- 该页插图 URL
);

create index if not exists idx_template_pages
  on template_pages (template_id, page_index);

-- ============ 互动游戏：个案档案 / 图片素材库 / 游戏局 ============

-- 孩子个案档案：诊断信息 + 能力侧重/偏弱 + 兴趣，用于定制出题
create table if not exists children (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  nickname    varchar not null,       -- 化名/小名
  age         integer,                -- 年龄
  gender      varchar,                -- 'boy' | 'girl' | 其他
  diagnosis   varchar,                -- 诊断类型：ASD / 智力迟缓 / ADHD 等
  severity    varchar,                -- 程度：轻度/中度/重度
  strengths   text[] default '{}',    -- 能力侧重（较强）
  weaknesses  text[] default '{}',    -- 偏弱方向（重点训练）
  interests   text[] default '{}'     -- 兴趣偏好（用于替换题材）
);

comment on table children is '孩子个案档案（定制出题依据）';

-- 兼容已建库：补积分累计列（互动游戏结算后累加）
alter table children add column if not exists total_points integer default 0 not null;

create index if not exists idx_children_user
  on children (user_id, created_at desc);

-- 图片素材库：AI 生成后转存对象存储的永久图，按标签复用
create table if not exists assets (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  kind        varchar not null,       -- 'emotion' | 'object' | 'scene'
  label       varchar not null,       -- 检索键：如 "开心" / "苹果"
  emotion     varchar,                -- 情绪键（kind=emotion 时）
  tags        text[] default '{}',    -- 附加标签（类别/颜色等）
  blob_url    varchar not null,       -- 永久 URL：Blob 直链，或 /api/asset/<id>（DB 兜底）
  data        text,                   -- 无 Blob token 时的 base64 兜底存储（data:image/...;base64,）
  source      varchar default 'ai',   -- 'ai' | 'manual'
  prompt      varchar                 -- 生成时的提示词
);

comment on table assets is '可复用图片素材库（永久地址）';

-- 兼容已建库：补 data 列（base64 兜底存储）
alter table assets add column if not exists data text;

create index if not exists idx_assets_kind_label
  on assets (kind, label);

create index if not exists idx_assets_user
  on assets (user_id);

-- 游戏局：一个孩子的一次出题结果（题目结构存 jsonb）
create table if not exists games (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  child_id    bigint references children(id) on delete set null,
  game_type   varchar not null,       -- 'emotion' | 'match'
  title       varchar,
  status      varchar,                -- BUILDING / READY / FAILED
  rounds      jsonb,                  -- 完整题目结构（含图 URL）
  config      jsonb                   -- 出题参数快照
);

comment on table games is '互动游戏局（定制题目）';

-- 兼容已建库：补反应类游戏（捉蝴蝶/打地鼠）结算字段
alter table games add column if not exists score integer;
alter table games add column if not exists stars integer;
alter table games add column if not exists difficulty varchar;

-- 软删（与 works/books/lesson_plans/chat_sessions 保持一致）
alter table games          add column if not exists deleted_at timestamptz;
alter table video_analyses add column if not exists deleted_at timestamptz;
create index if not exists idx_games_user_alive
  on games (user_id, updated_at desc) where deleted_at is null;
create index if not exists idx_videos_user_alive
  on video_analyses (user_id, updated_at desc) where deleted_at is null;

create index if not exists idx_games_user_created
  on games (user_id, created_at desc);

-- ============ 课堂视频分析（模块四）============

-- 一次课堂录像的 AI 分析结果：结构化报告存 jsonb
create table if not exists video_analyses (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  child_id    bigint references children(id) on delete set null,
  title       varchar,
  video_url   varchar,                -- 视频直链（测试链接 / Blob 永久地址）
  status      varchar,                -- ANALYZING / DONE / FAILED
  report      jsonb,                  -- 结构化报告（summary/childBehavior/teacherBehavior/timeline/stats/suggestions）
  error       varchar                 -- 失败原因
);

comment on table video_analyses is '课堂视频分析（孩子+老师课堂表现结构化报告）';

create index if not exists idx_videos_user_created
  on video_analyses (user_id, created_at desc);

-- ============ 全局侧栏额度区 ============

create table if not exists user_quotas (
  user_id     bigint primary key references users(id),
  total       integer not null default 100,
  remaining   integer not null default 100,
  updated_at  timestamptz default now() not null
);

comment on table user_quotas is '用户额度（全局侧栏额度区展示，首期固定额度，不做计费扣减）';

-- ============ 教案生成模块（ABA/DTT） ============

-- 教案：四层结构分列存储，便于逐字段读回校验与后续独立扩展某一层
create table if not exists lesson_plans (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now() not null,
  updated_at      timestamptz default now() not null,
  user_id         bigint references users(id),
  type            varchar default 'ABA-DTT',
  title           varchar,
  source          jsonb,            -- 教材来源引用：{kind, ref, chapter}
  duration        jsonb,            -- 时长控制：{lessonMinutes, trialWindowSec}
  goal_hierarchy  jsonb,            -- 第一层 目标体系：LTO -> Phase[] -> STO[]
  teaching_setup  jsonb,            -- 第二层 教学设置：教材/情景/策略/增强计划
  abc_procedure   jsonb,            -- 第三层 教学程序：A前因/B行为/C后果
  goal_checklist  jsonb             -- 目标清单：[{name, stoId, introducedDate, masteredDate}]
);

comment on table lesson_plans is '教案（ABA/DTT，四层结构分列存储）';

create index if not exists idx_lesson_plans_user_updated
  on lesson_plans (user_id, updated_at desc);

-- 教案模板：内置模板 user_id 为空，自定义模板归属具体用户
create table if not exists lesson_plan_templates (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  name        varchar not null,
  is_builtin  boolean default false not null,
  skill       varchar,            -- 技能类别：配对/模仿/命名…（内置模板用）
  content     jsonb not null      -- 预填的四层结构骨架
);

comment on table lesson_plan_templates is '教案模板（内置 + 我的模板）';

create index if not exists idx_lp_templates_user
  on lesson_plan_templates (user_id);

-- ============ 资源软删（Library 模块） ============
-- 图卡 / 绘本 / 教案 三类可被资源管理统一软删。deleted_at is null 表示未删除。
-- 列表查询与聚合接口均需过滤该字段；本期不做恢复 UI，仅数据保护。

alter table works        add column if not exists deleted_at timestamptz;
alter table books        add column if not exists deleted_at timestamptz;
alter table lesson_plans add column if not exists deleted_at timestamptz;

create index if not exists idx_works_user_alive
  on works (user_id, updated_at desc) where deleted_at is null;
create index if not exists idx_books_user_alive
  on books (user_id, updated_at desc) where deleted_at is null;
create index if not exists idx_lesson_plans_user_alive
  on lesson_plans (user_id, updated_at desc) where deleted_at is null;

-- ============ 小禾AI 对话会话 ============
-- 一次多轮对话 = 一行；messages jsonb 存整段消息数组 [{role, content}, ...]
-- 首条 user message 前 20 字作为 title；空对话不入表。
create table if not exists chat_sessions (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  title       varchar,
  messages    jsonb not null default '[]'::jsonb,
  deleted_at  timestamptz
);
comment on table chat_sessions is '小禾AI 对话会话（messages 存 jsonb 消息数组）';

create index if not exists idx_chat_sessions_user_alive
  on chat_sessions (user_id, updated_at desc) where deleted_at is null;

-- 兼容已建库：会话可绑定一个个案（首次发送时锁定，用于让 AI 记住"我在聊谁"）
alter table chat_sessions
  add column if not exists child_id bigint references children(id) on delete set null;

-- ============ 培训测评 · 模块五 ============
-- 学练测一体：康复师登录后学课程/做练习/答测评，出能力画像
-- 内容源：resources/class/riceai 培训视频文字内容.xlsx（逐字稿由 AI 二次加工为结构化学习稿）

-- 课程：从逐字稿结构化后的学习内容
create table if not exists training_courses (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now() not null,
  updated_at    timestamptz default now() not null,
  title         varchar not null,               -- 主题（对齐 xlsx 第 1 列）
  category      varchar not null,               -- aba/language/sensory/communication/assessment/platform/professionalism
  duration_min  integer,
  cover_url     varchar,
  video_url     varchar,                        -- 视频源（可空，早期仅稿）
  raw_transcript      text,                     -- xlsx 第 2 列：完整逐字稿
  raw_segments        jsonb,                    -- xlsx 第 3 列：带时间戳的分句数组
  outline       jsonb,                          -- AI 生成：[{title, start_sec, summary, key_points[], illust_prompt, illust_url}]
  key_takeaways jsonb,                          -- string[] 全课 5-8 条要点
  source_ref    varchar,                        -- 来源行号 "xlsx#row:N"
  status        varchar default 'draft',        -- draft/published
  deleted_at    timestamptz
);
comment on table training_courses is '培训测评 · 课程库';
create index if not exists idx_training_courses_alive
  on training_courses (category, updated_at desc) where deleted_at is null;

-- 课程进度：每个用户对每门课
create table if not exists training_course_progress (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now() not null,
  updated_at    timestamptz default now() not null,
  user_id       bigint references users(id) not null,
  course_id     bigint references training_courses(id) on delete cascade not null,
  progress_pct  integer default 0,              -- 0-100
  last_section  integer default 0,              -- 上次读到第几章
  completed_at  timestamptz,
  unique (user_id, course_id)
);
comment on table training_course_progress is '课程学习进度';

-- 练习场景（AI 情景模拟脚本）
create table if not exists training_scenarios (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now() not null,
  updated_at        timestamptz default now() not null,
  title             varchar not null,
  category          varchar not null,
  related_course_id bigint references training_courses(id) on delete set null,
  role_persona      jsonb,                      -- {who, tone, background}
  initial_message   text,                       -- AI 开场白
  evaluation_rubric jsonb,                      -- {dimensions:[{key,name,weight,criteria}]}
  success_criteria  jsonb,                      -- {min_rounds, max_rounds, must_hit_points[]}
  is_builtin        boolean default false,
  deleted_at        timestamptz
);
comment on table training_scenarios is '培训测评 · 练习场景（AI 情景模拟）';

-- 练习会话（一次角色扮演对话 = 一行）
create table if not exists training_practice_sessions (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now() not null,
  updated_at    timestamptz default now() not null,
  user_id       bigint references users(id) not null,
  scenario_id   bigint references training_scenarios(id) not null,
  messages      jsonb not null default '[]'::jsonb,
  evaluation    jsonb,                          -- {dimensions:{...scores}, highlights:[], improvements:[], overall}
  status        varchar default 'in_progress', -- in_progress/completed
  completed_at  timestamptz,
  deleted_at    timestamptz
);
comment on table training_practice_sessions is '培训测评 · 练习会话（不进"过去 30 天"）';
create index if not exists idx_training_practice_user_alive
  on training_practice_sessions (user_id, updated_at desc) where deleted_at is null;

-- 题目题库
create table if not exists training_questions (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now() not null,
  updated_at        timestamptz default now() not null,
  related_course_id bigint references training_courses(id) on delete cascade not null,
  category          varchar not null,
  difficulty        varchar default 'medium',   -- easy/medium/hard
  type              varchar not null,           -- single/judge/multi/case
  stem              text not null,
  options           jsonb not null,             -- [{key,text,is_correct,explain}]
  knowledge_points  jsonb default '[]'::jsonb,  -- string[]
  source_ref        varchar,                    -- 来源课的哪段（sentence_id 或 section title）
  status            varchar default 'published',-- draft/published
  deleted_at        timestamptz
);
comment on table training_questions is '培训测评 · 题库（题目强关联课程）';
create index if not exists idx_training_questions_course
  on training_questions (related_course_id) where deleted_at is null;

-- 测评卷（题目组合）
create table if not exists training_quizzes (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now() not null,
  updated_at    timestamptz default now() not null,
  title         varchar not null,
  category      varchar,
  description   text,
  question_ids  jsonb not null,                 -- bigint[]
  duration_min  integer,
  pass_score    integer default 60,
  is_builtin    boolean default false,
  deleted_at    timestamptz
);
comment on table training_quizzes is '培训测评 · 测评卷';

-- 用户测评记录（不允许软删，是学习审计数据）
create table if not exists training_quiz_attempts (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now() not null,
  user_id       bigint references users(id) not null,
  quiz_id       bigint references training_quizzes(id) not null,
  answers       jsonb not null default '[]'::jsonb, -- [{question_id, chosen:['A','C'], correct, time_ms}]
  score         integer,
  duration_sec  integer,
  submitted_at  timestamptz
);
comment on table training_quiz_attempts is '培训测评 · 用户答题记录';
create index if not exists idx_training_quiz_attempts_user
  on training_quiz_attempts (user_id, created_at desc);

-- ============ 培训测评 · 五维评测框架扩充 ============
-- 依据 resources/class/评测系统内容参考与维度设计.md
-- 领域 D1-D12 / 认知层级 L1-L5 / 岗位能力 C1-C6 / 关键项

-- 题目补列：认知层级、岗位能力、关键项、来源视频
alter table training_questions add column if not exists cognitive_level varchar; -- L1-L5
alter table training_questions add column if not exists competencies    jsonb default '[]'::jsonb; -- ["C1","C3"]
alter table training_questions add column if not exists is_key_item     boolean default false; -- 一票否决
alter table training_questions add column if not exists source_video    varchar; -- 来源培训视频标题

-- 兼容 case/multi/order 类型：老题库里 type 是 'single'|'judge'，现在扩展为 single/multi/judge/order/case

-- 知识点条目（16 条卡片，来自 md 第三节）
create table if not exists training_knowledge_items (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now() not null,
  updated_at        timestamptz default now() not null,
  code              varchar unique not null,    -- "KI-05" 之类，稳定引用
  domain            varchar not null,           -- D2/D3/D4 等
  title             varchar not null,           -- "ABC 行为分析模式"
  summary           text,                       -- 一段总结
  key_points        jsonb default '[]'::jsonb,  -- string[]
  common_mistakes   jsonb default '[]'::jsonb,  -- string[]（易错点，天然干扰项库）
  question_angles   jsonb default '[]'::jsonb,  -- string[]（可命题角度）
  source_videos     jsonb default '[]'::jsonb,  -- string[]（相关培训视频标题）
  sort              integer default 0,
  deleted_at        timestamptz
);
comment on table training_knowledge_items is '培训测评 · 知识点条目（出题依据）';

-- 题目 → 知识点条目关联（M:N，一题可能命中多个条目）
alter table training_questions add column if not exists knowledge_item_codes jsonb default '[]'::jsonb;

-- 题目可以脱离课程，直接挂在知识点条目上（放宽 not null）
alter table training_questions alter column related_course_id drop not null;
