-- 特需儿童教育绘本/图卡生成系统 —— 建表脚本
-- 可重复执行（IF NOT EXISTS）

create table if not exists users (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  username    varchar unique not null,   -- 登录账号
  password    varchar not null,          -- bcrypt 哈希
  nickname    varchar,                   -- 显示昵称
  avatar      varchar                    -- 头像 URL（可空）
);

comment on table users is '用户表（账号密码登录）';

create table if not exists works (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now() not null,
  updated_at   timestamptz default now() not null,
  user_id      bigint references users(id),
  template_id  varchar,                  -- 对应 data/templates.ts 的模板 key
  title        varchar,                  -- 作品标题（模板名+主体）
  input_text   varchar,                  -- 用户填写内容（JSON 字符串）
  prompt       varchar,                  -- 拼接后的最终正向提示词
  status       varchar,                  -- PENDING / RUNNING / SUCCEEDED / FAILED
  task_id      varchar,                  -- DashScope 异步任务 id
  output_url   varchar                   -- 生成图 URL（DashScope 临时地址，24h 有效）
);

comment on table works is '生成作品表';

create index if not exists idx_works_user_created
  on works (user_id, created_at desc);

create index if not exists idx_works_task
  on works (task_id);

-- ============ 多页绘本 ============

create table if not exists books (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  title       varchar,
  brief       varchar,          -- 用户输入的故事描述
  options     jsonb,            -- 生成参数（年龄/类型/主题/角色/视角/页数/比例）
  status      varchar,          -- DRAFTING / ILLUSTRATING / DONE / FAILED
  page_count  integer
);

comment on table books is '多页绘本';

create table if not exists book_pages (
  id          bigint generated by default as identity primary key,
  book_id     bigint references books(id) on delete cascade,
  page_index  integer,          -- 0 起
  text        varchar,          -- 该页故事正文
  scene       varchar,          -- 该页画面描述（喂给生图）
  task_id     varchar,          -- 该页 DashScope 生图任务 id
  status      varchar,          -- PENDING/RUNNING/SUCCEEDED/FAILED
  image_url   varchar
);

comment on table book_pages is '绘本分页';

create index if not exists idx_books_user_created
  on books (user_id, created_at desc);

create index if not exists idx_pages_book
  on book_pages (book_id, page_index);

-- ============ 预设模板库 ============

create table if not exists templates (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  kind        varchar,        -- 'image' | 'book'
  topic       varchar,        -- 康复课题：language/social/selfcare/cognition
  style_key   varchar,        -- 风格 key
  title       varchar,
  subtitle    varchar,
  brief       varchar,        -- 预设生成描述（点模板后填入输入框）
  options     jsonb,          -- 预设参数
  prompt      varchar,        -- 生成缩略图用的最终提示词
  cover_url   varchar,        -- 预生成的缩略图 URL
  sort        integer default 0
);

comment on table templates is '预设模板库';

create index if not exists idx_templates_kind_topic
  on templates (kind, topic);

-- 模板多页内容（绘本模板的逐页图文；图片模板可不建页）
create table if not exists template_pages (
  id           bigint generated by default as identity primary key,
  template_id  bigint references templates(id) on delete cascade,
  page_index   integer,       -- 0 起
  text         varchar,       -- 该页故事正文
  image_url    varchar        -- 该页插图 URL
);

create index if not exists idx_template_pages
  on template_pages (template_id, page_index);

-- ============ 互动游戏：个案档案 / 图片素材库 / 游戏局 ============

-- 孩子个案档案：诊断信息 + 能力侧重/偏弱 + 兴趣，用于定制出题
create table if not exists children (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  nickname    varchar not null,       -- 化名/小名
  age         integer,                -- 年龄
  gender      varchar,                -- 'boy' | 'girl' | 其他
  diagnosis   varchar,                -- 诊断类型：ASD / 智力迟缓 / ADHD 等
  severity    varchar,                -- 程度：轻度/中度/重度
  strengths   text[] default '{}',    -- 能力侧重（较强）
  weaknesses  text[] default '{}',    -- 偏弱方向（重点训练）
  interests   text[] default '{}'     -- 兴趣偏好（用于替换题材）
);

comment on table children is '孩子个案档案（定制出题依据）';

create index if not exists idx_children_user
  on children (user_id, created_at desc);

-- 图片素材库：AI 生成后转存对象存储的永久图，按标签复用
create table if not exists assets (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  kind        varchar not null,       -- 'emotion' | 'object' | 'scene'
  label       varchar not null,       -- 检索键：如 "开心" / "苹果"
  emotion     varchar,                -- 情绪键（kind=emotion 时）
  tags        text[] default '{}',    -- 附加标签（类别/颜色等）
  blob_url    varchar not null,       -- 永久 URL：Blob 直链，或 /api/asset/<id>（DB 兜底）
  data        text,                   -- 无 Blob token 时的 base64 兜底存储（data:image/...;base64,）
  source      varchar default 'ai',   -- 'ai' | 'manual'
  prompt      varchar                 -- 生成时的提示词
);

comment on table assets is '可复用图片素材库（永久地址）';

-- 兼容已建库：补 data 列（base64 兜底存储）
alter table assets add column if not exists data text;

create index if not exists idx_assets_kind_label
  on assets (kind, label);

create index if not exists idx_assets_user
  on assets (user_id);

-- 游戏局：一个孩子的一次出题结果（题目结构存 jsonb）
create table if not exists games (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null,
  user_id     bigint references users(id),
  child_id    bigint references children(id) on delete set null,
  game_type   varchar not null,       -- 'emotion' | 'match'
  title       varchar,
  status      varchar,                -- BUILDING / READY / FAILED
  rounds      jsonb,                  -- 完整题目结构（含图 URL）
  config      jsonb                   -- 出题参数快照
);

comment on table games is '互动游戏局（定制题目）';

create index if not exists idx_games_user_created
  on games (user_id, created_at desc);
